### PR TITLE
Integrate Scintilla

### PR DESCRIPTION
**Pull request by Awti**
- Add method call to register scintilla
- Adding to cgo build flags
- Removing call to MustLoadDLL (unnecessary)

### CODE REVIEW

**Comment by apmckinlay** [comment]
Should we include libscintilla.a ?
Otherwise if you just clone from git you won't be able to build.
It's a bit large, but should be ok

**Comment by Awti** [comment]
Its in there. Just really small

**Comment by Awti** [comment]
Just before builtin/msgloop_windows.go 

It's a binary file so it doesn't show anything for data really

**Comment by apmckinlay** [comment]
Sorry, missed it

**Comment by Awti** [comment]
No problemo, I missed it at first glance too

**Pull request merged**
